name: Test Runner

on:
    schedule:
        - cron: '*/2 * * * *'
    workflow_dispatch:
        inputs:
            python_version:
                description: 'Python version'
                required: true
                default: '3.13.2'
                type: string
    push:
    pull_request:

jobs:
    Run-Tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: ${{ github.event.inputs.python_version }}
            - name: Display Python version
              run: |
                  echo "Using Python version: ${{ github.event.inputs.python_version }}"
            - name: Install dependencies
              run: |
                    chmod +x -R ${{ github.workspace }}
                    python3 -m pip install --upgrade pip
                    python3 -m pip install -r requirements.txt
                    export PYTHONPATH="${PYTHONPATH}:${{github.workspace}}"
                    echo "PYTHONPATH=${PYTHONPATH}"
            - name: Run tests
              run: python3 -m pytest -s tests/part_01/test_users.py --junitxml=tests/results.xml --html=tests/results.html
            - name: Create test summary

              uses: test-summary/action@dist
              if: success() || failure()
              with:
                paths: tests/results.xml

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                name: test-results
                path: |
                    tests/results.xml
                    tests/results.html
                    assets

            - name: Notify Slack - Build Status
              if: always()
              uses: rtCamp/action-slack-notify@v2
              env:
                      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                      SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
                      SLACK_MESSAGE: |
                        ${{ job.status == 'success' && '✅ Python Tests completed successfully' || '❌ Python Tests failed' }} 
                        on branch *${{ github.ref_name }}* by *${{ github.actor }}*.
                        Details: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View on GitHub>
                      SLACK_TITLE: "Build Status: ${{ job.status }}"

            - name: Send Build Status Email
              uses: dawidd6/action-send-mail@v3
              if: always()
              with:
                      server_address: ${{ secrets.LSMTP_SERVER }}
                      server_port: ${{ secrets.LSMTP_PORT }}
                      username: ${{ secrets.LSMTP_USERNAME }}
                      password: ${{ secrets.LSMTP_PASSWORD }}
                      subject: "${{ job.status == 'success' && '✅ Build Succeeded' || '❌ Build Failed' }} - ${{ github.repository }}"
                      html_body: >
                        <!DOCTYPE html><html><body>
                        <h2>${{ job.status == 'success' && '✅ Build Succeeded' || '❌ Build Failed' }}</h2>
                        <p>Repository: <b>${{ github.repository }}</b></p>
                        <p>Commit: <b>${{ github.sha }}</b></p>
                        <p>Branch: <b>${{ github.ref_name }}</b></p>
                        <p>Check the details on <a href="${{ github.server_url }}/actions">GitHub Actions</a>.</p>
                        </body></html>
                      to: ${{ secrets.LRECIPIENT_EMAIL }}
                      from: ${{ secrets.LSMTP_USERNAME }}